### ISSUE TITLE
Shopify orders synced in purplship for fulfilment 

### ISSUE THREAD

**Issue by DanH91** [purplship/purplship-server#106]
**Is your feature request related to a problem? Please describe.**

I did like to get my Shopify orders imported in purplship. 

**Describe the solution you'd like**

- Would be great to import orders from Shopify 
- Would be nice to get Shopify orders synced with purplship as they come in 

**Additional context**

The Shopify REST API Webhook is a great way to notify Purplship of incoming orders.

**Comment by firxworx** [comment]
Could this be considered scope creep for purplship server specifically?

It seems like it could be a whole new project's scope - far beyond a multi-carrier shipping API which is a substantial problem in its own right - to create something like a ShipStation (and the zillions of other competing services that do the same thing). A great many users on Shopify etc. use these types of services to import orders and manage shipments, and they in turn integrate with shipping carriers (e.g. https://www.shipstation.com/partners/).

You might also want to look at integration players like CartRover.

**Comment by DanH91** [comment]
I agree it is a specific integration use case.
It is beyond the scope
